### ISSUE TITLE
Entrega de repositório da aula prática de refactoring

### ISSUE THREAD

**Issue by mtov** [mtov/AulaPraticaRefactoring#1]

**Comment by Tomas-Tamantini** [comment]
Tomás Tamantini - https://github.com/Tomas-Tamantini/refactoring.git

**Comment by matheusbuldrini** [comment]
Matheus Buldrini - https://github.com/matheusbuldrini/refactoring

**Comment by deizianens** [comment]
Deiziane Natani da Silva : https://github.com/grrl/refactoring/tree/master/src/refactoring

**Comment by AgnesBG** [comment]
Agnes Braune Guedes: https://github.com/AgnesBG/Refactoring_ES

**Comment by flavluc** [comment]
Flávio Lúcio Corrêa Júnior https://github.com/flaviolc18/refac

**Comment by NickolasLeal001** [comment]
Nickolas Victor Lima Lins Leal https://github.com/NickolasLeal001/Refactoring1

**Comment by Marcos30004347** [comment]
Marcos Vinicius Moreira Santos: https://github.com/Marcos30004347/Refactoring

**Comment by juliatiemi** [comment]
Julia Tiemi Alkmim Morishita: https://github.com/juliatiemi/AulaPraticaRefactoring

**Comment by afmarcelino** [comment]
Ana Flávia Araújo Marcelino: https://github.com/afmarcelino/roteiro-refactoring

**Comment by eduveraneio** [comment]
Eduardo Paulo de Oliveira: https://github.com/eduveraneio/AulaPraticaRefactoring

**Comment by ed-villani** [comment]
Eduardo Villani https://github.com/ed-villani/Refactoring

**Comment by lucascarneiro10** [comment]
Lucas de Castro Carneiro https://github.com/lucascarneiro10/refactoring

**Comment by antoniokht** [comment]
Antônio Côrtes Rodrigues: https://github.com/antoniokht/AulaPraticaRefactoring

**Comment by jvmota** [comment]
Jhonatan Vinícius Mota Corrêa: https://github.com/jvmota/AulaRefactoringESUFMG

**Comment by mhamendes** [comment]
Matheus Henrique Araújo Mendes: https://github.com/mhamendes/Refactoring

**Comment by renato-lopes** [comment]
Renato Sérgio Lopes Júnior - https://github.com/renato-junior/ES-Refactoring

**Comment by rlgc20** [comment]
Ronaldo Lucas Garcia Chaves: https://github.com/rlgc20/Refactoring

**Comment by luisareis13** [comment]
Luísa Pereira Reis: https://github.com/luisareis13/Refactoring

**Comment by pedro-maciel** [comment]
Pedro Henrique Almeida Maciel: https://github.com/pedro-maciel/Pratica-Refactoring

**Comment by brenoam** [comment]
Breno Augusto Martins: https://github.com/brenoam/AulaPraticaRefactoring

**Comment by haneybarg** [comment]
Fernanda Guimarães de Araújo [refactoring](https://github.com/haneybarg-es/refactoring)

**Comment by ghost** [comment]
André Franco Rios Catapani: https://github.com/andre-frc/Aula-Pratica-sobre-Refactoring

**Comment by gagaero** [comment]
Gabriel Rodrigues de Oliveira: https://github.com/gagaero/aula2

**Comment by marciorasf** [comment]
Marcio Roberto Andrade Souza Filho - https://github.com/marciorasf/Refactoring

**Comment by motheuslima** [comment]
[Matheus Henrique Antunes Lima](https://github.com/mathunesz/SWE_LISTA11)
