### ISSUE TITLE
Entrega de repositório da aula prática de refactoring - 2019/2

### ISSUE THREAD

**Issue by mtov** [mtov/AulaPraticaRefactoring#3]
Apenas responda a essa issue com seu nome e a URL do repositório que usou no exercício.

**Comment by GustavoA1604** [comment]
Nome: Gustavo Emanuel Faria Araújo
Repositório: https://github.com/GustavoA1604/Eng.Soft.Refactoring/

**Comment by henriqueup** [comment]
Henrique Urban Pessoa
https://github.com/henriqueup/EngSoft-AulaPraticaRefactoring

**Comment by diegobsilveira** [comment]
Diego Barros da Silveira
https://github.com/diegobsilveira/soft-eng-refactoring-class/

**Comment by thiagommohallem** [comment]
Thiago Matos Mohallem
https://github.com/thiagommohallem/AtividadeRefactoring/

**Comment by pardini01** [comment]
Rafael Alexandre Pardini Guedes
https://github.com/pardini01/AulaPraticaRefactoring

**Comment by GabiNeme** [comment]
Gabriela Peres Neme
https://github.com/GabiNeme/engsoft-refactoring

**Comment by jvtamm** [comment]
Nome: João Victor Moreira Tamm
https://github.com/jvtamm/ES-AulaPraticaRefactoring

**Comment by ssdasilva** [comment]
Nome: Samuel Souza da Silva
Repositório: https://github.com/ssdasilva/AulaPraticaRefactoring

**Comment by matheushsouza** [comment]
Matheus Henrique de Souza
https://github.com/matheushsouza/engsoft-aula-refactoring

**Comment by Macmod** [comment]
Artur Henrique Marzano Gonzaga
https://github.com/Macmod/EngSoftRefactoring

**Comment by LarissaGomes** [comment]
Larissa Gomes Malagoli
https://github.com/LarissaGomes/AulaPraticaRefactoring

**Comment by brunodemattos** [comment]
Bruno Demattos Nogueira
https://github.com/brunodemattos/Refactoring

**Comment by brenopoggiali** [comment]
Breno Poggiali de Sousa
https://github.com/brenopoggiali/AulaPraticaRefectoring

**Comment by jgobi** [comment]
João Gabriel de Oliveira Bicalho
https://github.com/jgobi/engsoft-20192-exref

**Comment by jonathanaas** [comment]
Jonathan Alves Alonso Soalheiro
https://github.com/jonathanaas/AulaPraticaRefactoring

**Comment by brenomatos** [comment]
Breno de Sousa Matos
https://github.com/brenomatos/refactoring-practice

**Comment by luizacbcampos** [comment]
Luiza Chagas Brandão Campos
https://github.com/luizacbcampos/AulaPraticaRefactoring

**Comment by VictorRodB** [comment]
Victor Rodrigues Barbosa
https://github.com/VictorRodB/ESoftRefactoring

**Comment by Jvccampos** [comment]
João Vítor Campos Teixeira 
https://github.com/Jvccampos/aulaRefactoring

**Comment by anaciriaco** [comment]
Ana Flávia Ciríaco Moura
https://github.com/anaciriaco/AulaPraticaRefactoring

**Comment by PedroPrisxzma** [comment]
Pedro Nascimento Costa
Repo: https://github.com/PedroPrisxzma/EngSoftAulaRefactoring

**Comment by semaraugusto** [comment]
Semar Augusto da Cunha Mello Martins
https://github.com/semaraugusto/AulaPraticaRefactoring

**Comment by sabtorres** [comment]
Guilherme Alvarenga Torres
https://github.com/torresguilherme/aula-pratica-refactoring

**Comment by adlermferreira** [comment]
Adler Melgaço Ferreira
https://github.com/adlermferreira/AulaPraticaRefactoring

**Comment by GabrielEspeschit** [comment]
Gabriel Saraiva Espeschit
https://github.com/GabrielEspeschit/TP-Refacroting.git

**Comment by jonatascavalcante** [comment]
Nome: Jonatas Cavalcante
URL: https://github.com/jonatascavalcante/dcc603_refactoring_practice

**Comment by rennancl** [comment]
Rennan Cordeiro Lima
https://github.com/rennancordeiro/refactoring-assingment

**Comment by GabrielPerson** [comment]
Gabriel de Person Pereira de Melo
https://github.com/GabrielPerson/Eng-Soft-Refactoring

**Comment by franciscogaluppo** [comment]
Francisco Galuppo Azevedo
https://github.com/franciscogaluppo/Refatora-o

**Comment by bernardo-torres** [comment]
Bernardo Ferreira Torres
https://github.com/torresbf/AulaRefactoring

**Comment by Thaisoares** [comment]
Thaís Soares Lamas
https://github.com/Thaisoares/Refactoring

**Comment by enokjrocha** [comment]
Enok Januário da Rocha
https://github.com/enokjrocha/ES_Refactoring

**Comment by guilhermedrud** [comment]
Guilherme Drummond Lima
https://github.com/guilhermedrud/Refact

**Comment by voidmarcus** [comment]
Marcus Vinicius de Oliveira
https://github.com/voidmarcus/Refactoring

**Comment by orlandoenrico** [comment]
Orlando Enrico Liz Silvério Silva
[https://github.com/orlandoenrico/Refactoring](https://github.com/orlandoenrico/Refactoring)

**Comment by josecoliveira** [comment]
José Carlos de Oliveira Júnior
https://github.com/joseoliveirajr/engsoft-ref

**Comment by TaynaraCruz** [comment]
Taynara Lorraine Marcelino da Cruz
https://github.com/TaynaraCruz/refactoring-Aula-Pratica

**Comment by scarletgv** [comment]
Scarlet Gianasi Viana
https://github.com/scarletgv/EDS-Refactoring

**Comment by Marcelo-Lemos** [comment]
Marcelo Luiz Harry Diniz Lemos
https://github.com/Marcelo-Lemos/AulaPraticaRefactoring

**Comment by Amanda1102** [comment]
Amanda Alkmim Rezende Teixeira
https://github.com/Amanda1102/AulaPraticaRefactoring

**Comment by italolsimas** [comment]
Nome : Italo lopes Simas
https://github.com/italolsimas/AulaRefactoring

**Comment by ingridlagares** [comment]
Nome: Ingrid Lagares Santana
https://github.com/ingridlagares/EngSoft-Refactoring

**Comment by matvargas** [comment]
**Nome:** Matheus Filipe Sieiro Vargas
[https://github.com/matvargas/Refactoring](https://github.com/matvargas/Refactoring)

**Comment by anagontijo** [comment]
Ana Carolina Gontijo Graça
https://github.com/anagontijo/RefactoringEngSoft2019-2016074242

**Comment by AugustoPolizer** [comment]
Augusto Henrique Polizer
https://github.com/AugustoPolizer/Pratica_Refactoring

**Comment by brunomaletta** [comment]
Bruno Maletta Monteiro
https://github.com/brunomaletta/engsoft2

**Comment by fernandaars** [comment]
Nome: Fernanda Aparecida Rodrigues Silva
Repositório: https://github.com/fernandaars/software_engineering

**Comment by bernardocipriano** [comment]
Bernardo Figueiredo Cipriano
https://github.com/CrimsonSycophant/AulaRefactoring

**Comment by alexandrehgpaiva** [comment]
Alexandre Henrique Garcia de Paiva
https://github.com/alexandrehgpaiva/AulaPraticaRefactoring

**Comment by ketlynsena** [comment]
Ketlyn Caroline Sena de Castro
https://github.com/ketlynsena/AulaPraticaRefactoring

**Comment by lauraabreusv** [comment]
Nome: Laura Abreu Schulz Vieira
https://github.com/lauraabreusv/AulaPraticaRefactoring

**Comment by gabrielspires** [comment]
Gabriel Henrique Souto Pires
https://github.com/gabrielspires/Pratica-Refactoring

**Comment by joaoh9** [comment]
Nome: João Henrique Soares Almeida Costa
https://github.com/joaoh9/engsoft20192

**Comment by joaopaulolara** [comment]
João Paulo Lara
https://github.com/joaopaulolara/aula_refactoring

**Comment by PDRIN** [comment]
Nome: Pedro Elias Valadares Castanheira
https://github.com/PDRIN/RefactoringClass

**Comment by MarcelHMendes** [comment]
Nome: Marcel Henrique da SIlva Mendes
https://github.com/MarcelHMendes/AulaRefactoring

**Comment by Geminimax** [comment]
Nome: Hiago de Souza Cruz Alves e Silva
https://github.com/Geminimax/AulaPraticaRefactoring
