### ISSUE TITLE
Issue usada para informar o repositório usado na aula prática de refactoring - 2020/1

### ISSUE THREAD

**Issue by mtov** [mtov/AulaPraticaRefactoring#5]
Basta adicionar um comentário aqui, com:

* seu nome
* URL do repositório que usou na aula.

**Comment by gabrielsluz** [comment]
Gabriel Santos Luz
https://github.com/gabrielsluz/AulaPraticaRefactoring

**Comment by joaomcouto** [comment]
João Marcos Couto
https://github.com/joaomcouto/ES-Refactoring_Lab

**Comment by igor-ma** [comment]
Igor Marques de Araújo
https://github.com/igor-ma/igor-ma_pratica_refact

**Comment by arthursl12** [comment]
Arthur Souto Lima
https://github.com/arthursl12/Refactoring_ES

**Comment by igorhenri5** [comment]
Igor Henrique Firmo e Santos
https://github.com/igorhenri5/Refactoring-Class

**Comment by ThiagoPoppe** [comment]
Thiago Martin Poppe
https://github.com/ThiagoPoppe/AulaPraticaRefactoring

**Comment by LorenaMendes** [comment]
Lorena Mendes Peixoto
https://github.com/LorenaMendes/refactoring

**Comment by EvandroLucas** [comment]
Evandro Lucas Figueiredo Teixeira
https://github.com/EvandroLucas/Refactoring-ES

**Comment by VictorHSMoura** [comment]
Victor Hugo Silva Moura
https://github.com/VictorHSMoura/EngSoft-Refactoring

**Comment by gabreuvcr** [comment]
Gabriel Victor Carvalho Rocha
https://github.com/gabreuvcr/pratica-refactoring

**Comment by vitorhgomes** [comment]
Vitor Henrique da Costa Gomes
[https://github.com/vitorhgomes/AulaPraticaRefactoring](https://github.com/vitorhgomes/AulaPraticaRefactoring)

**Comment by elvesmrodrigues** [comment]
Elves Mateus Rodrigues
https://github.com/elvesrodrigues/es-refactoring

**Comment by barbaragribeiro** [comment]
Bárbara Gomes Ribeiro
https://github.com/barbaragribeiro/engsoft-refactoring

**Comment by lucasbrant** [comment]
Lucas Mariani Paiva Caldeira Brant
https://github.com/lucasbrant/Pratica2_Refatora-o_ES

**Comment by mtfr1** [comment]
Mateus Figueiredo
[https://github.com/mtfr1/es-refactoring/](https://github.com/mtfr1/es-refactoring)

**Comment by guilhermeleroy** [comment]
Luiz Guilherme Leroy Vieira
https://github.com/guilhermeleroy/Refactoring-EngSoft

**Comment by Maharal** [comment]
Raphael Augusto Teixeira Silva
https://github.com/Maharal/AulaPraticaRefactoring

**Comment by FranciscoPDNeto** [comment]
Francisco de Paula Dias Neto
https://github.com/FranciscoPDNeto/es_Refactoring

**Comment by guilhermebezerrads** [comment]
Guilherme Bezerra dos Santos
https://github.com/guilhermebezerrads/AulaPraticaRefactoring

**Comment by aaraujo-main** [comment]
Alan Prado Araújo
https://github.com/AlaoPrado/EngSoft_EP2

**Comment by Goncalves-Rafael** [comment]
Rafael Gonçalves de Oliveira
https://github.com/Goncalves-Rafael/AulaRefactoring

**Comment by luizhemelo** [comment]
Luiz Henrique de Melo Santos
https://github.com/luizhemelo/ES_AulaPratica02_Refactoring

**Comment by marscos** [comment]
Marcos Carvalho de Assis
https://github.com/marscos/aula_refactoring

**Comment by luiz-couto** [comment]
Luiz Felipe Couto Gontijo
https://github.com/luiz-couto/LocadoraRefactoring

**Comment by maTh51** [comment]
Matheus Tiago Pimenta de Souza
https://github.com/maTh51/Refactoring_Maven_Eng_Soft

**Comment by vfrezende** [comment]
Vitor Franco Rezende
https://github.com/vfrezende/AulaPraticaRefactoring

**Comment by guilhermealbm** [comment]
Guilherme de Abreu Lima Buitrago Miranda
https://github.com/guilhermealbm/EngSoft_Aula_Refactoring

**Comment by jufs128** [comment]
Júlia Fonseca de Sena
https://github.com/jufs128/AulaPratica_Refactoring

**Comment by brunacmelo** [comment]
Bruna Campos de Melo
https://github.com/brunacmelo/aularefactoring

**Comment by fseppe** [comment]
Felipe Seppe de Faria
https://github.com/fseppe/AulaPraticaRefactoring

**Comment by davi-v** [comment]
Davi Braga Tolentino Veloso
https://github.com/davi-v/EngSoftAulaRefactoring

**Comment by gabriel-cangucu** [comment]
Gabriel Lima Canguçu
https://github.com/gabriel-cangucu/AulaPraticaRefactoring

**Comment by BVarella** [comment]
Bruno Varella Peixoto
https://github.com/BVarella/AulaPraticaRefactoring

**Comment by felipecadar** [comment]
Felipe Cadar Chamone
[https://github.com/felipecadar/AP2-EngSoft](https://github.com/felipecadar/AP2-EngSoft)

**Comment by marcotmotta** [comment]
Marco Túlio Motta de Jesus
https://github.com/marcotmotta/refactoring-es

**Comment by lucaspellegrinelli** [comment]
Lucas Resende Pellegrinelli Machado
https://github.com/lucaspellegrinelli/eng-software-refactoring

**Comment by gabrielapaixao** [comment]
Gabriela Pereira Faria Paixão
https://github.com/gabrielapaixao/AulaPraticaRefactoring

**Comment by isadoracristina** [comment]
Isadora Cristina de Matos Rodrigues
https://github.com/isadoracristina/Pratica_Refactoring

**Comment by LucasStarlingdePaulaSalles** [comment]
Lucas Starling De Paula Salles
https://github.com/LucasStarlingdePaulaSalles/AulaRefactor

**Comment by lorenaleao** [comment]
Lorena Raphaela Diniz Leão
https://github.com/lorenaleao/refactoring-practice

**Comment by anaflvm** [comment]
Ana Flávia de Miranda Silva
https://github.com/anaflvm/EngSoft-Refactoring

**Comment by LuanFranco98** [comment]
Luan Silveira Franco
https://github.com/LuanFranco98/EngSoft_Pratica_Refactoring

**Comment by isadorasalles** [comment]
Isadora Alves de Salles 
https://github.com/isadorasalles/EngSoft-Refactoring

**Comment by vrjuliao** [comment]
Vinicius Julião Ramos
https://github.com/vrjuliao/engsoft-aulapratica-refactoring

**Comment by caioguedesam** [comment]
Caio Guedes de Azevedo Mota
https://github.com/caioguedesam/AulaPratica_Refactoring

**Comment by Henrique-Brito** [comment]
Henrique Junqueira de Brito
https://github.com/Henrique-Brito/TP_Refactoring

**Comment by gilouzi** [comment]
Giovanna Louzi Bellonia
https://github.com/gilouzi/AulaPraticaRefactoring

**Comment by tomaz1502** [comment]
Tomaz Gomes Mascarenhas
https://github.com/tomaz1502/refactoring-engsoft/

**Comment by alvaro-rodrigues** [comment]
Álvaro Machado Rodrigues
https://github.com/alvaro-rodrigues/esRefactoring

**Comment by daniel-leite** [comment]
Daniel Leite Ribeiro
https://github.com/daniel-leite/EngSoft-Pratica-2

**Comment by felipelrib** [comment]
Felipe dos Santos Leão Ribeiro
https://github.com/felipelrib/AulaPraticaRefactoring
